import React from 'react'
import Head from 'next/head'

export default function Home() {
  const generateState = (length) => {
    var result           = '';
    var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for ( var i = 0; i < length; i++ ) {
      result += characters.charAt(Math.floor(Math.random() *  charactersLength));
   }
   return result;
  }

  const codeUrl = 'https://www.figma.com/oauth?client_id='+ process.env.NEXT_PUBLIC_FIGMA_CLIENT_ID +'&redirect_uri='+ process.env.NEXT_PUBLIC_FIGMA_REDIRECT_URI +'&scope=file_read&state='+ generateState(10) +'&response_type=code'

  return (
    <React.Fragment>
      <Head>
        <title>Fabric</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={`px-8 h-body flex items-center justify-center py-10`}>
        <div className={`container mx-auto`}>
          <div className='w-full'>
            <h1 className={`m-0 leading-tight text-5xl text-center`}>
              Welcome to <span className={`text-blue-700`}>Fabric</span>
            </h1>

            <div className='flex items-center justify-center py-10'>
              <a
                href={codeUrl}
                className="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-base uppercase px-5 py-2.5 text-center mr-2 mb-2"
                rel='noreferrer'
              >
                Connect Figma Account
              </a>
            </div>
          </div>
        </div>
      </main>
    </React.Fragment>
  )
}
